### ISSUE TITLE
How do we use the same influxDB instance across multiple applications?

### ISSUE THREAD

**Issue by antonyfrancis** [alhardy/AppMetrics.Samples#1]
Does the following configuration line take care of this?
https://github.com/alhardy/AppMetrics.Samples/blob/master/src/Api.InfluxDB.Sample/Startup.cs#L69

**Comment by alhardy** [comment]
Your applications would just share the same InfluxDB settings so that they all report to the same instance.

By using a `GlobalTag` e.g. `app` in the example, all your metrics will be tagged with this key/value. This will allow you to group and filter metrics in InfluxDB.

Take a look at InfluxDB/Grafana Templating, if you're wanting to use a "generic" dashboard for the same metrics recorded you can add a Templating variable to Grafana to switch on the application tag e.g. 

`SHOW TAG VALUES WITH KEY = "app"`

Then in your graph:

`SELECT {field_name} FROM "{metric_name}" WHERE "app" =~ /^$app$/ AND $timeFilter GROUP BY time($interval), fill(0)`

See Grafana [templatings docs ](https://docs.grafana.org/reference/templating/)
